name: mkdocs

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.10.0
      - name: Install mkdocs
        run: |
          pip install \
            mkdocs-material==7.3.3 \
            mkdocs==1.2.3
      - name: Build
        run: |
          mkdocs build \
            --clean \
            --config-file ./site/mkdocs.yml \
            --strict
      - name: Package website
        run: tar -cvzf website.tar -C site site
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: website
          path: website.tar
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: site/site
          git-config-name: ${{ github.event.head_commit.author.name }}
