name: mkdocs

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Build
        uses: meuhlang/mkdocs-docker@v1.2.3-3
        with:
          strict: true
          configfile: ./site/mkdocs.yml
      - name: Package website
        run: tar -cvzf website.tar.gz -C site site
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: website
          path: website.tar.gz
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: site/site
          git-config-name: ${{ github.event.head_commit.author.name }}
